### ISSUE TITLE
您好，想麻烦问一下，我发现现在的仓库里丢失了很多msg文件，请问去哪里可以下载呢？

### ISSUE THREAD

**Issue by Supergithubber** [Derek-TH-Wang/quadruped_ctrl#11]

**Comment by Supergithubber** [comment]
Hi, I miss whole_body_state_msg.msg. Where can I download these MSG files?
Looking forward to your reply! @eborghi10

**Comment by eborghi10** [comment]
Hi @Supergithubber, I realized that I didn't have issue-posting enabled in my fork. You can now open tickets [there](https://github.com/eborghi10/quadruped_ctrl) if you prefer.

Regarding the missing message files, if you're confident working with Docker, [here](https://github.com/RoboticaUtnFrba/robotica_aplicada_docker/blob/master/legged.dockerfile) is the one that I use. If you prefer to install the dependencies by yourself, check [this list](https://github.com/RoboticaUtnFrba/robotica_aplicada_docker/blob/master/legged.repos): be aware that I'm using my own fork for one of the repositories because the maintainers didn't merge my PR yet.

Best.

**Comment by Supergithubber** [comment]
> 

Thank you so much!
